version: '3.1'

services:
  mysql:
   image: mysql
   restart: always
   container_name: moviesdb
   ports:
    - 3307:3306
   environment:
     MYSQL_HOST: localhost
     MYSQL_DATABASE: movies
     MYSQL_ROOT_PASSWORD: movies321
   volumes:
    - ./dump:/docker-entrypoint-initdb.d